<?php

$form = $this->form;
$form->setAttribute('action', $this->url('user', array('action' => 'authenticate')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('rememberMe'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();