<?php
// module/User/view/user/index/login.phtml:

$title = 'Add new user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('register', array('action' => 'register')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('email'));
echo $this->formHidden($form->get('status'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();