<?php
// module/Album/view/album/album/index.phtml:
$title = 'My events';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1> 
<table class="table">
    <tr>
        <th>Event name</th>
        <th>Start</th>
        <th>End</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($events as $event) : ?> 
        <tr>
            <td><?php echo $this->escapeHtml($event->eventName); ?></td>
            <td><?php echo $this->escapeHtml($event->start->format('Y-m-d H:i:s')); ?></td>
            <td><?php echo $this->escapeHtml($event->start->format('Y-m-d H:i:s')); ?></td> 
        </tr>
    <?php endforeach; ?> 
</table>